version: "3.1"
services:
  mysql:
    image: mysql:5.6
    container_name: halcyon-mysql
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=halcyon #${DB_PASSWORD}
      # - MYSQL_ROOT_USER=${DB_USERNAME}
      - MYSQL_DATABASE=halcyon #${DB_DATABASE}
      - MYSQL_USER=root #${DB_USERNAME}
    ports:
      - "8082:3306"
    volumes:
      - ./storage/dump:/docker-entrypoint-initdb.d
      - ./storage/mysql:/var/lib/mysql
      - .:/var/www/html
    #env_file: .env
    networks:
      - halcyon

  webserver:
    image: nginx:alpine
    container_name: halcyon-webserver
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./docker/ssl/server.key:/etc/ssl/private/server.key
      - ./storage/logs:/var/log/nginx
      - .:/var/www/html
      - ./storage/app/public:/var/www/html/public/files
    ports:
      - "80:80"
      - "443:443"
    networks:
      - halcyon

  php-fpm:
    build: docker/php-fpm
    container_name: halcyon-php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php7.2/fpm/conf.d/99-overrides.ini
      - ./storage/app/public:/var/www/html/public/files
    networks:
      - halcyon

  node:
    build:
      context: ./docker/node
    image: halcyon/node:latest
    volumes:
      - .:/var/www/html
    networks:
      - halcyon

#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    ports:
#      - 6379:6379
#    networks:
#      - halcyon

#  mailhog:
#    image: mailhog/mailhog:latest
#    container_name: mailhog
#    ports:
#      - 1025:1025
#      - 8025:8025
#    networks:
#      - halcyon

networks:
  halcyon:
