version: "3.1"
services:

    # Database
    mysql:
      image: mysql:5.6
      container_name: halcyon-mysql
      working_dir: /var/www/html
      environment:
        - MYSQL_ROOT_PASSWORD="${DB_PASSWORD}"
        - MYSQL_DATABASE="${DB_DATABASE}"
        - MYSQL_USER="${DB_USERNAME}"
      ports:
        - "8082:3306"
      volumes:
        - ./storage/mysql:/var/lib/mysql
        - .:/var/www/html
      env_file: .env

    # Web server
    webserver:
      image: nginx:alpine
      container_name: halcyon-webserver
      restart: unless-stopped
      working_dir: /var/www/html
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./docker/ssl/server.crt:/etc/ssl/certs/server.crt
        - ./docker/ssl/server.key:/etc/ssl/private/server.key
        - ./storage/logs:/var/log/nginx
        - .:/var/www/html
      ports:
        - "80:80"
        - "443:443"

    php-fpm:
      build: docker/php-fpm
      container_name: halcyon-php-fpm
      restart: unless-stopped
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php7.2/fpm/conf.d/99-overrides.ini
