name: PHP Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      #- name: Linting Code
      #  uses: github/super-linter@v4
      #  env:
      #    VALIDATE_ALL_CODEBASE: false
      #    VALIDATE_PHP: true
      #    DEFAULT_BRANCH: master
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Linting Code
        uses: overtrue/phplint@8.2
        with:
          path: .
          options: --exclude=*.log